services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./jenkins-slo-alerts.yml:/etc/prometheus/jenkins-slo-alerts.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring-net
      - kind

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring-net
    depends_on:
      - prometheus

networks:
  monitoring-net:
    driver: bridge
  kind:
    external: true
