sonar.projectKey=taskflow-api
sonar.projectName=taskflow-api
sonar.projectVersion=1.0.0
sonar.host.url=http://host.docker.internal:9000

# Source & Test paths
sonar.sources=apps/server/src
sonar.tests=apps/server/test,apps/server/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/reports/**,**/*.spec.ts

# Coverage & Test execution reporting
sonar.javascript.lcov.reportPaths=apps/server/coverage/lcov.info,coverage/lcov.info
sonar.testExecutionReportPaths=apps/server/reports/junit.xml,reports/junit.xml
