apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subtracker-api-hpa
  labels:
    app.kubernetes.io/name: subtracker-api-hpa
    app.kubernetes.io/part-of: subscription-track
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subtracker-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    # ขยาย Pod เมื่อ CPU เฉลี่ยพุ่งเกิน 70%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
          
    # ขยาย Pod เมื่อ RAM เฉลี่ยพุ่งเกิน 80%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
