apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subtracker-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: subtracker-infra
    app.kubernetes.io/part-of: subscription-track
spec:
  project: default
  source:
    repoURL: 'https://github.com/nawaphonST1/subscription_track.git'
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
